### ISSUE TITLE
Front - Crash on showNotification

### ISSUE THREAD

**Issue by lcubeddu** [XPEHO/XpeApp#95]
Application crashed upon clicking on one of the newsletter entries. Logs show it was trying to call `NewsletterNotication.showNotification`

Relevant error message:

```
showNotification
Compat change id reported: 160794467; UID 10190; state: ENABLED
--------- beginning of crash
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.xpeho.xpeapp, PID: 2809
java.lang.IllegalArgumentException: com.xpeho.xpeapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:428)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:544)
	at android.app.PendingIntent.getActivity(PendingIntent.java:530)
	at android.app.PendingIntent.getActivity(PendingIntent.java:494)
	at com.xpeho.xpeapp.ui.componants.NewsletterNotification.showNotification(NewsletterNotification.kt:33)
	at com.xpeho.xpeapp.data.service.MyFirebaseMessagingService$onMessageReceived$1.invokeSuspend(MyFirebaseMessagingService.kt:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2cf26c2, Dispatchers.Default]

```

**Comment by lcubeddu** [comment]
From https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability :

Pending intents mutability

If your app targets Android 12, you must [specify the mutability](https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent) of each [PendingIntent](https://developer.android.com/reference/android/app/PendingIntent) object that your app creates. This additional requirement improves your app's security.
